# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "2f5fef1068c7f69ac4ef3a6015cd0bffcfac1b8fc7bea526e0d711cac26e96af"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b36410093988985602742002870be7e5d5085fb6a4f0d1ae6b1f9517e89a34fa"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58a1062ebcd9c5f229e846ffeccc70c47e32f4cf4fe84bfd7380bbccabca4936"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb0829ec12827c5642acb8fb39a936af16f035267a91c1c8032fb9ee3b1f0c03"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "CLI tool for Git worktree management and safety guardrails"
  homepage "https://github.com/servusdei2018/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required

end
