# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "40ae124beb69ffe5996b042e6b3ea885e3855d1ff5571db52282ffed8da22a23"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "96bbc6825aab30ab4ca868045e1677a6e4caf4aae8bbabbb478636d7e3831fa5"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d4c2db2074731251e7d48d7eb06f8681f97a583a037e9d14f153005392c700b"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e755d6e7920d8bc6e974fac161d6c1806d3abc6ec5248f0982be076211eaf854"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "CLI tool for Git worktree management and safety guardrails"
  homepage "https://github.com/servusdei2018/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required

end
