# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "d0622fb13498f6fb29a51342a7a67b30b6f45b78a44d20510ee0ea7ed184110a"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "39e50692a370d78241d1a4bb53e45925ec3a661ed6d41c87361a847b3092d218"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e013da95cc6de31f22f9cfa43ddbd6253c35a937f6929579bdc447ddde887424"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "616d59ba806315f9799030ae4ee19bc63f2e5b183cf0de0a8523e9580f14661a"
      url "https://github.com/servusdei2018/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "CLI tool for Git worktree management and safety guardrails"
  homepage "https://github.com/servusdei2018/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required

end
