# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "CLI tool for Git worktree management and safety guardrails"
  homepage "https://github.com/servusdei2018/wt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/servusdei2018/wt/releases/download/v0.1.0/wt_0.1.0_darwin_amd64.tar.gz"
      sha256 "9330865f4e849cb34ef4c2f4af18aa304062007f4e8c4d57a240f022fa4fb50d"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/servusdei2018/wt/releases/download/v0.1.0/wt_0.1.0_darwin_arm64.tar.gz"
      sha256 "3fbc1b312061f600709b40a3ce787bb41477f7d7a40144ef342ac107e5c4b622"

      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/servusdei2018/wt/releases/download/v0.1.0/wt_0.1.0_linux_amd64.tar.gz"
      sha256 "ebf4ba4d60c26fe6bc42eee87ce4776fa17921e89aeed66bbbd2864f0d934681"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/servusdei2018/wt/releases/download/v0.1.0/wt_0.1.0_linux_arm64.tar.gz"
      sha256 "24b0fcd0de911a09b947d540b8a4a5dbbee0edfab53b5cc8a41b8dd443644cf1"
      define_method(:install) do
        bin.install "wt"
        generate_completions_from_executable(bin/"wt", "completion")
      end
    end
  end

  test do
    assert_match "wt manages Git worktrees", shell_output("#{bin}/wt --help")
  end
end
